### ISSUE TITLE
 Error when execute run_build_dataset.sh (missing depickle.py in gtrans/data_process/)

### ISSUE THREAD

**Issue by Legitao** [AI-nstein/hoppity#2]
Hi, when I was executing run_build_dataset.sh with raw JS pairs, it raised an error:

> SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/zhutao/lab/hoppity/gtrans/data_process/find_all_refs.js:268:12)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11

I found in gtrans/data_process/find_all_refs.js:265, the line `var ast = spawnSync("python", [HOPPITY_HOME + "/depickle.py", ast_file])` executes depicke.py file. But it seems this file is missing in the repo. This results in ast to be `undefined`, which leads to the error above.

Could you @Hanjun-Dai @elizabethdinella add this depickle.py file to the repo? Thank you very much.

**Comment by elizabethdinella** [comment]
Pushed the `depickle.py` file. Sorry about that!
